/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BowlersRouteImport } from './routes/bowlers'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as EventsRouteImport } from './routes/events'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HubRouteImport } from './routes/hub'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as MoreRouteImport } from './routes/more'
import { Route as NewsRouteImport } from './routes/news'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as TeamsRouteImport } from './routes/teams'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BowlersRoute = BowlersRouteImport.update({
  id: '/bowlers',
  path: '/bowlers',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bowlers': typeof BowlersRoute
  '/deposit': typeof DepositRoute
  '/events': typeof EventsRoute
  '/home': typeof HomeRoute
  '/hub': typeof HubRoute
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/more': typeof MoreRoute
  '/news': typeof NewsRoute
  '/onboarding': typeof OnboardingRoute
  '/owner': typeof OwnerRoute
  '/rankings': typeof RankingsRoute
  '/rules': typeof RulesRoute
  '/signup': typeof SignupRoute
  '/standings': typeof StandingsRoute
  '/teams': typeof TeamsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bowlers': typeof BowlersRoute
  '/deposit': typeof DepositRoute
  '/events': typeof EventsRoute
  '/home': typeof HomeRoute
  '/hub': typeof HubRoute
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/more': typeof MoreRoute
  '/news': typeof NewsRoute
  '/onboarding': typeof OnboardingRoute
  '/owner': typeof OwnerRoute
  '/rankings': typeof RankingsRoute
  '/rules': typeof RulesRoute
  '/signup': typeof SignupRoute
  '/standings': typeof StandingsRoute
  '/teams': typeof TeamsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bowlers': typeof BowlersRoute
  '/deposit': typeof DepositRoute
  '/events': typeof EventsRoute
  '/home': typeof HomeRoute
  '/hub': typeof HubRoute
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/more': typeof MoreRoute
  '/news': typeof NewsRoute
  '/onboarding': typeof OnboardingRoute
  '/owner': typeof OwnerRoute
  '/rankings': typeof RankingsRoute
  '/rules': typeof RulesRoute
  '/signup': typeof SignupRoute
  '/standings': typeof StandingsRoute
  '/teams': typeof TeamsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bowlers'
    | '/deposit'
    | '/events'
    | '/home'
    | '/hub'
    | '/login'
    | '/merch'
    | '/more'
    | '/news'
    | '/onboarding'
    | '/owner'
    | '/rankings'
    | '/rules'
    | '/signup'
    | '/standings'
    | '/teams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bowlers'
    | '/deposit'
    | '/events'
    | '/home'
    | '/hub'
    | '/login'
    | '/merch'
    | '/more'
    | '/news'
    | '/onboarding'
    | '/owner'
    | '/rankings'
    | '/rules'
    | '/signup'
    | '/standings'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bowlers'
    | '/deposit'
    | '/events'
    | '/home'
    | '/hub'
    | '/login'
    | '/merch'
    | '/more'
    | '/news'
    | '/onboarding'
    | '/owner'
    | '/rankings'
    | '/rules'
    | '/signup'
    | '/standings'
    | '/teams'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BowlersRoute: typeof BowlersRoute
  DepositRoute: typeof DepositRoute
  EventsRoute: typeof EventsRoute
  HomeRoute: typeof HomeRoute
  HubRoute: typeof HubRoute
  LoginRoute: typeof LoginRoute
  MerchRoute: typeof MerchRoute
  MoreRoute: typeof MoreRoute
  NewsRoute: typeof NewsRoute
  OnboardingRoute: typeof OnboardingRoute
  OwnerRoute: typeof OwnerRoute
  RankingsRoute: typeof RankingsRoute
  RulesRoute: typeof RulesRoute
  SignupRoute: typeof SignupRoute
  StandingsRoute: typeof StandingsRoute
  TeamsRoute: typeof TeamsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bowlers': {
      id: '/bowlers'
      path: '/bowlers'
      fullPath: '/bowlers'
      preLoaderRoute: typeof BowlersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BowlersRoute: BowlersRoute,
  DepositRoute: DepositRoute,
  EventsRoute: EventsRoute,
  HomeRoute: HomeRoute,
  HubRoute: HubRoute,
  LoginRoute: LoginRoute,
  MerchRoute: MerchRoute,
  MoreRoute: MoreRoute,
  NewsRoute: NewsRoute,
  OnboardingRoute: OnboardingRoute,
  OwnerRoute: OwnerRoute,
  RankingsRoute: RankingsRoute,
  RulesRoute: RulesRoute,
  SignupRoute: SignupRoute,
  StandingsRoute: StandingsRoute,
  TeamsRoute: TeamsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
